### ISSUE TITLE
Feature request: capability of stripping-out 4-byte utf8 characters

### ISSUE THREAD

**Issue by jogaco** [whitequark/rack-utf8_sanitizer#24]
For a non utf8-mb4 mysql database storage backend.

**Comment by bf4** [comment]
Funny, I just had this error myself:

```
Incorrect string value: '\xF0\x9F\x98\x8A ' for column
```

Since we had

```
  utf8mb4_message = "Just because. Thank you 😊 "
```

I chose to resolve this by changing the adapter to use the `utf8mb4` encoding and altered the table: `ALTER TABLE thing_with_message MODIFY COLUMN message VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL`

I wonder if it might make sense to add a 'max byte size' configuration and have it default to not set, but in this case, I would set it to '3', or '4' depending on what I want to allow.]

- https://dev.mysql.com/doc/refman/5.6/en/charset-connection.html
- https://dev.mysql.com/doc/refman/5.6/en/charset-unicode-utf8mb4.html
- https://mathiasbynens.be/notes/mysql-utf8mb4
  > Never use utf8 in MySQL — always use utf8mb4 instead. Updating your databases and code might take some time, but it’s definitely worth the effort. Why would you arbitrarily limit the set of symbols that can be used in your database? Why would you lose data every time a user enters an astral symbol as part of a comment or message or whatever it is you store in your database? There’s no reason not to strive for full Unicode support everywhere. Do the right thing, and use utf8mb4. 🍻
- http://tech.taskrabbit.com/blog/2014/04/24/active-record-mysql-and-emoji/

**Comment by jogaco** [comment]
Not all apps need support for emojis, so this option would certainly be helpful.

**Comment by whitequark** [comment]
This is now possible to do in a custom strategy in your application since #41.
